version: 2.1
orbs:   #paquete reutilizable que contiene comandos, jobs y ejecutores predefinidos 
  sonarcloud: sonarsource/sonarcloud@2.0.0
executors:
  node:
    docker:
      - image: cimg/node:20.5.1

jobs: # el job que va a ejecutar el workflow
  test:
    working_directory: ~/project
    executor: node
    steps:
      - checkout # Descarga el código del repositorio

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run lint
          command: npm run lint:report

      - run:
          name: Run tests
          command: npm run test:coverage

      - store_test_results:
          path: test-results.xml
      - sonarcloud/scan    

      - persist_to_workspace:
          root: ~/project   # Guardar para utilizar posteriormente en el siguiente job
          paths: .

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Debug Workspace
          command: ls -la ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Pack package
          command: npm pack
      - run:
          name: Publish package
          command: npm publish --dry run
      - store_artifacts:
          path: ~/repo/my-awesome-package-1.1.0.tgz
          destination: package/release.tgz
      - store_artifacts:
          path: ~/repo/dist
          destination: dist
      - store_artifacts:
          path: ~/repo/docs
          destination: docs
workflows:
  test-and-deploy: # el job al que va a llamar el workflow
    jobs:
      - test:
          context: SonarCloud
      - deploy:
          requires:
            - test