version: 2.1

orbs:   # Paquete reutilizable que contiene comandos, jobs y ejecutores predefinidos 
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  node:
    docker:
      - image: cimg/node:20.5.1

jobs: # Definici칩n de jobs
  test:
    working_directory: ~/project
    executor: node
    steps:
      - checkout # Descarga el c칩digo del repositorio

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run lint
          command: npm run lint:report

      - run:
          name: Run tests
          command: npm run test:coverage

      - store_test_results:
          path: test-results.xml
      
      - sonarcloud/scan  # Ejecuta el an치lisis de c칩digo en SonarCloud

      - persist_to_workspace:
          root: ~/project   # Guarda los archivos para utilizarlos en otro job
          paths: .

  build:
    working_directory: /tmp
    executor: node
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Debug Workspace
          command: ls -la ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/project/.npmrc
      - run:
          name: Pack package
          command: npm pack
      - run:
          name: Publish package
          command: npm publish --dry-run
      - store_artifacts:
          path: ~/project/my-awesome-package-1.1.0.tgz
          destination: package/release.tgz
      - store_artifacts:
          path: ~/project/dist
          destination: dist
      - store_artifacts:
          path: ~/project/docs
          destination: docs

workflows:
  test-and-deploy: # Flujo de trabajo que ejecuta los jobs
    jobs:
      - test:
          context: SonarCloud
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
